baseURL: https://hal.guru
title: hal.guru
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
pluralizelisttitles: yes
markup:
  goldmark:
    renderer:
      unsafe: no
params:
  author: hal.guru
  copyright: © hal.guru sp. z o.o.
  photoURL: images/photo.jpg
  terms: /terms
  dateFormat: January 2, 2006
  description: hal.guru - AI Agents that work, for you
  keywords: hal.guru,blog,ai,agents,robots,rpa,llm,artificial intelligence,robotic process automation,chatgpt,chatbot,chatbots,chat,gpt,ai,artificial intelligence,robot,robots,robotics,automation,automate,automating,automated,automates,automatization,automatize,automatizing,automatized,automatizes,automatization,agentic,agent
  maxSeeAlsoItems: 5
  rtl: no
  colorScheme: auto
  hideColorSchemeToogle: no
  since: 2023
  hubspot:
    id: 14558022
  googleTagManager:
    id: G-V25YW0BSFY
  giscus:
    repo: HAL-guru/hal.guru
    repoID: R_kgDOLJEgsQ
    reactionsEnabled: yes
    crossorigin: anonymous
    mapping: title
    loading: lazy
    category: Blog
    categoryID: DIC_kwDOLJEgsc4Ccrsa
    categories:
      en:
        category: Blog
        categoryID: DIC_kwDOLJEgsc4Ccrsa
      pl:
        category: Blog PL
        categoryID: DIC_kwDOLJEgsc4Ccrsb
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/hal-guru/hal.guru.Docs
      weight: 1
    - icon: fa fa-2x fa-facebook
      name: Facebook
      url: https://www.facebook.com/groups/6214467021932639
      weight: 2
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/hal-guru/
      weight: 3
    - icon: fa fa-2x fa-medium
      name: Medium
      url: https://medium.com/hal-guru
      weight: 4
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    params:
      lead: AI Agents that work
      info: 
        - for you
      button: 
        title: Learn more
        url: manifesto/
      blog:
        title: Blog
    menu:
      main:
        - name: Manifesto
          url: manifesto/
          weight: 1
        - name: Solution
          url: solution/
          weight: 2
        - name: ROI
          url: roi/
          weight: 3
        - name: Technology
          url: technology/
          weight: 4
        - name: Blog
          url: blog/
          weight: 5
        - name: Contact
          url: contact/
          weight: 6
  pl:
    languageName: ':poland:'
    params:
      lead: Agenci AI, którzy działają
      info:
        - dla Ciebie
      button: 
        title: Dowiedz się więcej
        url: manifest/
      blog:
        title: Blog
    menu:
      main:
        - name: Manifest
          url: manifest/
          weight: 1
        - name: Rozwiązanie
          url: rozwiazanie/
          weight: 2
        - name: ROI
          url: zwrot-z-inwestycji/
          weight: 3
        - name: Technologia
          url: technologia/
          weight: 4
        - name: Blog
          url: blog/
          weight: 5
        - name: Kontakt 
          url: kontakt/
          weight: 5
