site_name: hal.guru docs
site_url: https://docs.hal.guru/
site_author: hal.guru
site_description: >-
  AI Agents that works, for you
repo_name: hal-guru/hal.guru
repo_url: https://github.com/HAL-guru/hal.guru.git

theme:
  name: material

nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Install halguru CLI': 'getting-started/01-install-halguru-cli.md'
  - 'halguru CLI':
    - 'HAL.Guru API': 'halguru-cli/index.md'
  - 'Configuring AI Agents':
    - 'Introduction': 'configuring-ai-agents/index.md'
  - About:
    - 'License': 'license.md'

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
plugins:
  - search
