site_name: docs.hal.guru
site_url: https://docs.hal.guru/
site_author: hal.guru
site_description: >-
  AI Agents that works, for you
repo_name: Download
repo_url: https://github.com/HAL-guru/hal.guru.git
copyright: Copyright &copy; 2025 hal.guru sp. z o.o.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HAL-guru/hal.guru
      name: hal.guru on GitHub
theme:
  name: material
  logo: icon-white.png
  favicon: favicon.svg
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    #- navigation.tabs
    #- navigation.sections
    #- navigation.expand
  extra_css:
    - overrides/custom.css
nav:
  - 'Welcome': 'index.md'
  - 'Installation':
      - 'Installation': 'installation/index.md'
      - '&nbsp;&nbsp;&nbsp;Details':
        - 'MacOS and Linux': 'installation/macos-and-linux.md'
        - 'Windows': 'installation/windows.md'
        - 'Experienced users': 'installation/experienced-users.md'
  - 'Getting Started':
    - 'My first agent AI': 'getting-started/01-install-halguru-cli.md'
  - 'Configuration files':
    - 'Configuration files': 'models/index.md'
# Autogenerated AgentConfiguration Begin
    - '.halguru.yaml': 'models/(halguru).md'
    - '&nbsp;&nbsp;&nbsp;Properties':
      - 'HalGuru': 'models/(halguru)-halguru.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'HalGuru': 'models/(halguru)-halguru.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'FilePurpose': 'models/(halguru)-halguru-filepurpose.md'
          - 'PlatformVersion': 'models/(halguru)-halguru-platformversion.md'
          - 'PlatformUrl': 'models/(halguru)-halguru-platformurl.md'
          - 'AutogeneratedAgentUrl': 'models/(halguru)-halguru-autogeneratedagenturl.md'
      - 'Agent': 'models/(halguru)-agent.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'Agent': 'models/(halguru)-agent.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'Id': 'models/(halguru)-agent-id.md'
          - 'Name': 'models/(halguru)-agent-name.md'
          - 'Type': 'models/(halguru)-agent-type.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'Type': 'models/(halguru)-agent-type.md'
          - 'Version': 'models/(halguru)-agent-version.md'
          - 'Description': 'models/(halguru)-agent-description.md'
          - 'Author': 'models/(halguru)-agent-author.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'Author': 'models/(halguru)-agent-author.md'
            - '&nbsp;&nbsp;&nbsp;Properties':
              - 'Name': 'models/(halguru)-agent-author-name.md'
              - 'Email': 'models/(halguru)-agent-author-email.md'
              - 'Url': 'models/(halguru)-agent-author-url.md'
              - 'Company': 'models/(halguru)-agent-author-company.md'
              - 'Copyright': 'models/(halguru)-agent-author-copyright.md'
          - 'Start': 'models/(halguru)-agent-start.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'Start': 'models/(halguru)-agent-start.md'
            - '&nbsp;&nbsp;&nbsp;Properties':
              - 'LlmConnectorName': 'models/(halguru)-agent-start-llmconnectorname.md'
              - 'PromptName': 'models/(halguru)-agent-start-promptname.md'
              - 'Url': 'models/(halguru)-agent-start-url.md'
          - 'Themes': 'models/(halguru)-agent-themes.md'
          - 'UI': 'models/(halguru)-agent-ui.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'UI': 'models/(halguru)-agent-ui.md'
            - '&nbsp;&nbsp;&nbsp;Properties':
              - 'DisableCloseButton': 'models/(halguru)-agent-ui-disableclosebutton.md'
          - 'Features': 'models/(halguru)-agent-features.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'Features': 'models/(halguru)-agent-features.md'
            - '&nbsp;&nbsp;&nbsp;Properties':
              - 'CheckAllUrls': 'models/(halguru)-agent-features-checkallurls.md'
              - 'CheckIsAnswerCorrect': 'models/(halguru)-agent-features-checkisanswercorrect.md'
              - 'CheckIsLastUrlCorrectAnswer': 'models/(halguru)-agent-features-checkislasturlcorrectanswer.md'
              - 'CommentCurrentUrl': 'models/(halguru)-agent-features-commentcurrenturl.md'
              - 'PerChannelThreading': 'models/(halguru)-agent-features-perchannelthreading.md'
              - 'MaxRetryAttempts': 'models/(halguru)-agent-features-maxretryattempts.md'
      - 'Operator': 'models/(halguru)-operator.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'Operator': 'models/(halguru)-operator.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'Name': 'models/(halguru)-operator-name.md'
          - 'UI': 'models/(halguru)-operator-ui.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'UI': 'models/(halguru)-operator-ui.md'
          - 'Features': 'models/(halguru)-operator-features.md'
          - '&nbsp;&nbsp;&nbsp;Properties':
            - 'Features': 'models/(halguru)-operator-features.md'
      - 'Messages': 'models/(halguru)-messages-list.md'
      - 'Prompts': 'models/(halguru)-prompts-list.md'
      - 'LlmConnectors': 'models/(halguru)-llmconnectors-list.md'
      - 'Secrets': 'models/(halguru)-secrets-list.md'
      - 'State': 'models/(halguru)-state.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - '.halguru-state.yaml': 'models/(state).md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'Started': 'models/(state)-started-list.md'
          - 'LastAccess': 'models/(state)-lastaccess-list.md'
          - 'IsStarted': 'models/(state)-isstarted-list.md'
          - 'ThreadId': 'models/(state)-threadid.md'
          - 'LlmConnectorName': 'models/(state)-llmconnectorname.md'
          - 'PromptName': 'models/(state)-promptname.md'
          - 'Url': 'models/(state)-url.md'
          - 'Language': 'models/(state)-language.md'
          - 'Description': 'models/(state)-description.md'
          - 'Variables': 'models/(state)-variables-list.md'
      - 'TestCases': 'models/(halguru)-testcases-list.md'
      - 'ExampleMessages': 'models/(halguru)-examplemessages-list.md'
# Autogenerated AgentConfiguration End
# Autogenerated StateConfiguration Begin
    - '.halguru-state.yaml': 'models/(state).md'
    - '&nbsp;&nbsp;&nbsp;Properties':
      - 'Started': 'models/(state)-started-list.md'
      - 'LastAccess': 'models/(state)-lastaccess-list.md'
      - 'IsStarted': 'models/(state)-isstarted-list.md'
      - 'ThreadId': 'models/(state)-threadid.md'
      - 'LlmConnectorName': 'models/(state)-llmconnectorname.md'
      - 'PromptName': 'models/(state)-promptname.md'
      - 'Url': 'models/(state)-url.md'
      - 'Language': 'models/(state)-language.md'
      - 'Description': 'models/(state)-description.md'
      - 'Variables': 'models/(state)-variables-list.md'
# Autogenerated StateConfiguration End
# Autogenerated ActionConfiguration Begin
    - '.halguru-action.yaml': 'models/(action).md'
    - '&nbsp;&nbsp;&nbsp;Properties':
      - 'Command': 'models/(action)-command.md'
      - 'RunSqlSelect': 'models/(action)-runsqlselect.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'RunSqlSelect': 'models/(action)-runsqlselect.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'DatabaseProvider': 'models/(action)-runsqlselect-databaseprovider.md'
          - 'ConnectionString': 'models/(action)-runsqlselect-connectionstring.md'
          - 'SqlQuery': 'models/(action)-runsqlselect-sqlquery.md'
          - 'Explanation': 'models/(action)-runsqlselect-explanation.md'
          - 'Result': 'models/(action)-runsqlselect-result.md'
      - 'SendToPipedrive': 'models/(action)-sendtopipedrive.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'SendToPipedrive': 'models/(action)-sendtopipedrive.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'Language': 'models/(action)-sendtopipedrive-language.md'
          - 'DealTitle': 'models/(action)-sendtopipedrive-dealtitle.md'
          - 'UserName': 'models/(action)-sendtopipedrive-username.md'
          - 'UserOrganisation': 'models/(action)-sendtopipedrive-userorganisation.md'
          - 'UserEmail': 'models/(action)-sendtopipedrive-useremail.md'
          - 'UserPhone': 'models/(action)-sendtopipedrive-userphone.md'
          - 'Description': 'models/(action)-sendtopipedrive-description.md'
      - 'ChangePrompt': 'models/(action)-changeprompt.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'ChangePrompt': 'models/(action)-changeprompt.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'Name': 'models/(action)-changeprompt-name.md'
      - 'ChangetLlmConnector': 'models/(action)-changetllmconnector.md'
      - '&nbsp;&nbsp;&nbsp;Properties':
        - 'ChangetLlmConnector': 'models/(action)-changetllmconnector.md'
        - '&nbsp;&nbsp;&nbsp;Properties':
          - 'Name': 'models/(action)-changetllmconnector-name.md'
# Autogenerated ActionConfiguration End
# Autogenerated WebsiteConfiguration Begin
    - '.halguru-website.yaml': 'models/(website).md'
    - '&nbsp;&nbsp;&nbsp;Properties':
      - 'StartUrl': 'models/(website)-starturl.md'
      - 'MaxLevel': 'models/(website)-maxlevel.md'
      - 'MaxPages': 'models/(website)-maxpages.md'
      - 'Pages': 'models/(website)-pages-list.md'
      - 'UrlsStartWith': 'models/(website)-urlsstartwith-list.md'
# Autogenerated WebsiteConfiguration End
  - 'halguru CLI':
    - 'Introduction': 'halguru-cli/index.md'
# Autogenerated CliCommands Begin
# Autogenerated CliCommands End
  - 'Schemas': 'schemas/index.md'

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
plugins:
  - search
