site_name: docs.hal.guru
site_url: https://docs.hal.guru/
site_author: hal.guru
site_description: >-
  AI Agents that works, for you
repo_name: Download
repo_url: https://github.com/HAL-guru/hal.guru.git
copyright: Copyright &copy; 2025 hal.guru sp. z o.o.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HAL-guru/hal.guru
      name: hal.guru on GitHub
theme:
  name: material
  logo: icon-white.png
  favicon: favicon.svg
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    #- navigation.tabs
    #- navigation.sections
    #- navigation.expand

nav:
  - 'Welcome': 'index.md'
  - 'Installation':
      - 'Installation': 'installation/index.md'
      - 'MacOS and Linux': 'installation/macos-and-linux.md'
      - 'Windows': 'installation/windows.md'
      - 'Experienced users': 'installation/experienced-users.md'
  - 'Getting Started':
    - 'My first agent AI': 'getting-started/01-install-halguru-cli.md'
  - 'Configuration files':
    - 'Configuration files': 'models/configuration-files.md'
# Autogenerated AgentConfiguration Begin
    - '.halguru.yaml': 'models/(halguru).md'

# Autogenerated AgentConfiguration End
# Autogenerated AgentConfiguration End
# Autogenerated AgentConfiguration End
# Autogenerated StateConfiguration Begin
    - '.halguru-state.yaml': 'models/(state).md'

# Autogenerated StateConfiguration End
# Autogenerated StateConfiguration End
# Autogenerated StateConfiguration End
# Autogenerated ActionConfiguration Begin
    - '.halguru-action.yaml': 'models/(action).md'

# Autogenerated ActionConfiguration End
# Autogenerated ActionConfiguration End
# Autogenerated ActionConfiguration End
# Autogenerated WebsiteConfiguration Begin
    - '.halguru-website.yaml': 'models/(website).md'

# Autogenerated WebsiteConfiguration End
# Autogenerated WebsiteConfiguration End
# Autogenerated WebsiteConfiguration End
  - 'halguru CLI':
    - 'Introduction': 'halguru-cli/index.md'
# Autogenerated CliCommands Begin
# Autogenerated CliCommands End
  - About:
    - 'License': 'license.md'

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
plugins:
  - search
