name: Release

on:
  push:
    tags:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest

    permissions:
      repository-projects: read
      contents: write
      packages: read

    steps:
      - name: halguru installation
        run: curl -sSL https://docs.hal.guru/installation/install.sh | bash
      - name: Determine version
        run: halguru --version
