name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      repository-projects: read
      contents: write
      packages: read

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          echo "version=$(cat docs/version.txt)" >> $GITHUB_OUTPUT
          echo ${{ steps.release.outputs.version }}

      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.release.outputs.version }}
          tag_name: ${{ steps.release.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: halguru installation
        run: curl -sSL https://docs.hal.guru/installation/install.sh | bash
      - name: Determine version
        run: halguru --version
